#!/usr/bin/env bash

##
# Automatically create, rotate and destroy BTRFS snapshots.
#
#
#

set -o errexit
set -o errtrace
set -o functrace
set -o nounset
set -o pipefail
#set -o xtrace

# shellcheck source=SCRIPTDIR/inc/args.bash
source "$(dirname "${0}" | xargs -d'\n' readlink -f -n | xargs -d'\n' printf '%s/inc/args.bash' || true)"

# shellcheck source=SCRIPTDIR/inc/snaps.bash
source "$(dirname "${0}" | xargs -d'\n' readlink -f -n | xargs -d'\n' printf '%s/inc/snaps.bash' || true)"

main() {
  args::parse "${@}"
  args::print_usage_and_exit_if

  snaps::do "${ARGS['subvols.paths']}"
  snaps::rm "${ARGS['subvols.paths']}"
}

main "${@}"
